#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $PG_MLFLOW_USER WITH PASSWORD '$PG_MLFLOW_PASSWORD';
	CREATE DATABASE $PG_MLFLOW_DB OWNER $PG_MLFLOW_USER;

    CREATE USER $PG_CELERY_USER WITH PASSWORD '$PG_CELERY_PASSWORD';
	CREATE DATABASE $PG_CELERY_DB OWNER $PG_CELERY_USER;
EOSQL