from enum import Enum


class EnvConfig(Enum):
    PORT = "PORT"
    ENVIRONMENT = "ENVIRONMENT"
    SWAGGER_DOCS_BASIC_AUTH_USERNAME = "SWAGGER_DOCS_BASIC_AUTH_USERNAME"
    SWAGGER_DOCS_BASIC_AUTH_PASSWORD = "SWAGGER_DOCS_BASIC_AUTH_PASSWORD"
    S3_ENDPOINT_URL = "S3_ENDPOINT_URL"
    S3_BUCKET_NAME = "AWS_DOCUMENTS_BUCKET_NAME"
    S3_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
    S3_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
    CELERY_BROKER_CONNECTION = "CELERY_BROKER_CONNECTION"
    CELERY_BACKEND_CONNECTION = "CELERY_BACKEND_CONNECTION"
    CELERY_DEFAULT_QUEUE = "CELERY_DEFAULT_QUEUE"
    DB_CONNECTION = "DB_CONNECTION"
    DB_DATABASE = "DB_DATABASE"
